/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface TodoList {
    }
    interface TodoSite {
    }
}
declare global {
    interface HTMLTodoListElement extends Components.TodoList, HTMLStencilElement {
    }
    var HTMLTodoListElement: {
        prototype: HTMLTodoListElement;
        new (): HTMLTodoListElement;
    };
    interface HTMLTodoSiteElement extends Components.TodoSite, HTMLStencilElement {
    }
    var HTMLTodoSiteElement: {
        prototype: HTMLTodoSiteElement;
        new (): HTMLTodoSiteElement;
    };
    interface HTMLElementTagNameMap {
        "todo-list": HTMLTodoListElement;
        "todo-site": HTMLTodoSiteElement;
    }
}
declare namespace LocalJSX {
    interface TodoList {
    }
    interface TodoSite {
    }
    interface IntrinsicElements {
        "todo-list": TodoList;
        "todo-site": TodoSite;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "todo-list": LocalJSX.TodoList & JSXBase.HTMLAttributes<HTMLTodoListElement>;
            "todo-site": LocalJSX.TodoSite & JSXBase.HTMLAttributes<HTMLTodoSiteElement>;
        }
    }
}
